name: DockerBuild

on:
  push:
    branches:
      - "master"
      - "docker"
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  DockerBuild:
    uses: ./.github/workflows/reusable_docker.yml
